/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BBMS.view;

import BBMS.controller.SearchBloodDonorByLocation;
import BBMS.controller.StockIncrease;
import BBMS.controller.UpdateDonorDetails;
import BBMS.controller.StockDecrease;
import BBMS.controller.DeleteDonor;
import BBMS.controller.AllDonorDetails;
import BBMS.controller.AddNewDonor;
import BBMS.controller.SearchBloodDonorByBloodGroup;
import BBMS.controller.SearchBloodDonorByCovidStatus;
import BBMS.controller.StockDetails;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Mr.Lucky
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        JFrame frame = (JFrame) SwingUtilities.getRoot(getContentPane());
        makeFrameFullSize(frame);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAddNewDonor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemUpdateDetails = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAllDonorDetails = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemByLocation = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemByBloodGroup = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemByCovidStatus = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemStockIncrease = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemStockDecrease = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemStockDetails = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemDeleteDonor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -290, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(233, 29, 36));
        jMenuBar1.setForeground(new java.awt.Color(233, 29, 36));

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Donor.png"))); // NOI18N
        jMenu6.setText("Donor");

        jMenuItemAddNewDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAddNewDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Add new.png"))); // NOI18N
        jMenuItemAddNewDonor.setText("Add New Donor");
        jMenuItemAddNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddNewDonorActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAddNewDonor);
        jMenu6.add(jSeparator1);

        jMenuItemUpdateDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUpdateDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Update details.png"))); // NOI18N
        jMenuItemUpdateDetails.setText("Update Details");
        jMenuItemUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateDetailsActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemUpdateDetails);
        jMenu6.add(jSeparator2);

        jMenuItemAllDonorDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAllDonorDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Details.png"))); // NOI18N
        jMenuItemAllDonorDetails.setText("All Donor Details");
        jMenuItemAllDonorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAllDonorDetailsActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAllDonorDetails);

        jMenuBar1.add(jMenu6);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/search user.png"))); // NOI18N
        jMenu2.setText("Search Blood Donor");

        jMenuItemByLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemByLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Location.png"))); // NOI18N
        jMenuItemByLocation.setText("By Location");
        jMenuItemByLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemByLocationActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemByLocation);
        jMenu2.add(jSeparator3);

        jMenuItemByBloodGroup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemByBloodGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Blood group.png"))); // NOI18N
        jMenuItemByBloodGroup.setText("By Blood Group");
        jMenuItemByBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemByBloodGroupActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemByBloodGroup);
        jMenu2.add(jSeparator7);

        jMenuItemByCovidStatus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemByCovidStatus.setText("By Covid Status");
        jMenuItemByCovidStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemByCovidStatusActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemByCovidStatus);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/stock.png"))); // NOI18N
        jMenu3.setText("Stock");

        jMenuItemStockIncrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemStockIncrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Inc.png"))); // NOI18N
        jMenuItemStockIncrease.setText("Increase");
        jMenuItemStockIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockIncreaseActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemStockIncrease);
        jMenu3.add(jSeparator4);

        jMenuItemStockDecrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemStockDecrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Dec.png"))); // NOI18N
        jMenuItemStockDecrease.setText("Decrease");
        jMenuItemStockDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockDecreaseActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemStockDecrease);
        jMenu3.add(jSeparator6);

        jMenuItemStockDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemStockDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Details.png"))); // NOI18N
        jMenuItemStockDetails.setText("Stock Details");
        jMenuItemStockDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStockDetailsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemStockDetails);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/delete donor.png"))); // NOI18N
        jMenu4.setText("Delete Donor");

        jMenuItemDeleteDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDeleteDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/delete.png"))); // NOI18N
        jMenuItemDeleteDonor.setText("Delete Donor");
        jMenuItemDeleteDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteDonorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemDeleteDonor);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/exit.png"))); // NOI18N
        jMenu5.setText("Exit");

        jMenuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Logout.png"))); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemLogout);
        jMenu5.add(jSeparator5);

        jMenuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BBMS/resources/Exit application.png"))); // NOI18N
        jMenuItemClose.setText("Close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemClose);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddNewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddNewDonorActionPerformed
        // TODO add your handling code here:
        new AddNewDonor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAddNewDonorActionPerformed

    private void jMenuItemByLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemByLocationActionPerformed
        // TODO add your handling code here:
        new SearchBloodDonorByLocation().setVisible(true);
    }//GEN-LAST:event_jMenuItemByLocationActionPerformed

    private void jMenuItemAllDonorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAllDonorDetailsActionPerformed
        // TODO add your handling code here:
        new AllDonorDetails().setVisible(true);
    }//GEN-LAST:event_jMenuItemAllDonorDetailsActionPerformed

    private void jMenuItemByBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemByBloodGroupActionPerformed
        // TODO add your handling code here:
        new SearchBloodDonorByBloodGroup().setVisible(true);
    }//GEN-LAST:event_jMenuItemByBloodGroupActionPerformed

    private void jMenuItemStockDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockDetailsActionPerformed
        // TODO add your handling code here:
        new StockDetails().setVisible(true);
    }//GEN-LAST:event_jMenuItemStockDetailsActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Do you want to Exit?","Blood Bank Management System",
                JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Do you want to Logout?","Blood Bank Management System",
                JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateDetailsActionPerformed
        // TODO add your handling code here:
        new UpdateDonorDetails().setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateDetailsActionPerformed

    private void jMenuItemStockIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockIncreaseActionPerformed
        // TODO add your handling code here:
        new StockIncrease().setVisible(true);
    }//GEN-LAST:event_jMenuItemStockIncreaseActionPerformed

    private void jMenuItemStockDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStockDecreaseActionPerformed
        // TODO add your handling code here:
        new StockDecrease().setVisible(true);
    }//GEN-LAST:event_jMenuItemStockDecreaseActionPerformed

    private void jMenuItemDeleteDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteDonorActionPerformed
        // TODO add your handling code here:
        new DeleteDonor().setVisible(true);
    }//GEN-LAST:event_jMenuItemDeleteDonorActionPerformed

    private void jMenuItemByCovidStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemByCovidStatusActionPerformed
        // TODO add your handling code here:
         new SearchBloodDonorByCovidStatus().setVisible(true);
    }//GEN-LAST:event_jMenuItemByCovidStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }
    private void makeFrameFullSize(JFrame aFrame) {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    aFrame.setSize(screenSize.width/2, screenSize.height/2);
    aFrame.setLocation(screenSize.width/8,screenSize.height/8);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAddNewDonor;
    private javax.swing.JMenuItem jMenuItemAllDonorDetails;
    private javax.swing.JMenuItem jMenuItemByBloodGroup;
    private javax.swing.JMenuItem jMenuItemByCovidStatus;
    private javax.swing.JMenuItem jMenuItemByLocation;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemDeleteDonor;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemStockDecrease;
    private javax.swing.JMenuItem jMenuItemStockDetails;
    private javax.swing.JMenuItem jMenuItemStockIncrease;
    private javax.swing.JMenuItem jMenuItemUpdateDetails;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
